CREATE TABLE users (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL,
    password varchar(50) NOT NULL
);

INSERT INTO users (username, password) VALUES ("test", "test");